### ISSUE TITLE
Get token for manipulating Organization Projects

### ISSUE THREAD

**Issue by RothAndrew** [octo-sts/action#22]
Loving Octo STS so far! I'm working on setting up some simple proofs of concept. One thing I'd like to do is use it to get a short lived token to be used to add an issue to an Organization Project. I see that the GitHub App did request and receive read/write access to Organization Projects, but I'm not seeing a clear way to use it.

<img width="972" alt="image" src="https://github.com/octo-sts/action/assets/16000938/8fff9926-3812-442f-b6a8-038170cb456f">

AFAIK the list of scopes that you are able to put in the `permissions:` section of the trust policy are specified in [this doc](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs#overview), but org projects are not included in the scopes there, just repository projects (a.k.a. "classic" projects).

How do I set up a trust policy such that I would be able to add a github issue to an org project?

**Comment by RothAndrew** [comment]
I may be on the cusp of answering my own question. The [blog post](https://www.chainguard.dev/unchained/the-end-of-github-pats-you-cant-leak-what-you-dont-have) mentions putting org-level trust policies in the org's `.github` repo, and I'm thinking I may be able to use the scope `project` as documented [here](https://docs.github.com/en/apps/oauth-apps/building-oauth-apps/scopes-for-oauth-apps#available-scopes)

**Comment by RothAndrew** [comment]
Got it working. Instructions:

> The org I used is called `rothandrew-octo-sts-testing`. Substitute that with whatever your org name is.

1. Add the octo-sts app to your org
1. Add file `.github/chainguard/org-project.sts.yaml` to your org's `.github` repo (the special one) with contents:
	```yaml
	# Purpose: Give repos in the org the ability to add issues to org projects
	
	issuer: https://token.actions.githubusercontent.com
	
	# Allow any repo in the org to have write access to org projects.
	# It would be nice if I was able to use "repo:rothandrew-octo-sts-testing/.*:issues" as the subject pattern, in order to limit the runs to only ones that come from the "issues" event, but unfortunately it looks like the workflow always uses "repo:<org>/<repo>:ref:refs/heads/main" as the subject when issue events run.
	# (":issues" format derived from this doc: https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/about-security-hardening-with-openid-connect#filtering-for-pull_request-events)
	# TODO: Format the subject_pattern such that there is an allowlist of certain repos, rather than giving blanket permission to all repos
	subject_pattern: repo:rothandrew-octo-sts-testing/.*:ref:refs/heads/main
	
	permissions:
	  organization_projects: write
	```
1. Add file `.github/workflows/auto-assign-to-project.yaml` to any repo in the org with contents:
	```yaml
	name: auto-assign-to-project
	on:
	  issues:
	    types:
	      - opened
	
	permissions:
	  id-token: write # Needed to federate with octo-sts
	
	jobs:
	  add-to-project:
	    name: Add issue to project
	    runs-on: ubuntu-latest
	    steps:
	      - uses: octo-sts/action@6177b4481c00308b3839969c3eca88c96a91775f # v1.0.0
	        id: octo-sts
	        with:
	          scope: ${{ github.repository_owner }}
	          identity: org-project
	      - uses: actions/add-to-project@9bfe908f2eaa7ba10340b31e314148fcfe6a2458 # v1.0.1
	        with:
	          # Don't forget to change the Project ID to whichever project you want to put things in
	          project-url: https://github.com/orgs/${{ github.repository_owner }}/projects/1
	          github-token: ${{ steps.octo-sts.outputs.token }}
	```
1. Create an issue in the repo

![image](https://github.com/octo-sts/action/assets/16000938/9d052c11-d8a7-4283-918e-d704ea63304f)
