### ISSUE TITLE
Support changing the endpoint of Octo STS for Self hosting

### ISSUE THREAD

**Issue by suzuki-shunsuke** [octo-sts/action#26]
Now the endpoint of Octo STS is hardcoded to `https://octo-sts.dev/sts/exchange`.

https://github.com/octo-sts/action/blob/3622e4d541c8adbc31c21017a7025ef418b94c09/index.js#L42

To use this action with self-hosted Octo STS, we need to change the endpoint.
So how about adding an optional input variable `endpoint` to change the endpoint?
The default value is `https://octo-sts.dev/sts/exchange`.

e.g.

```yaml
- uses: octo-sts/action@main
  id: octo-sts
  with:
    scope: your-org/your-repo
    identity: foo
    endpoint: https://example.com/sts/exchange
```
