### ISSUE TITLE
Can't generate a token on github action

### ISSUE THREAD

**Issue by aqemia-aymeric-alixe** [octo-sts/action#30]
# Errors

Hello,

We have installed octosts app on our github org with rights on all repos.
We have created a permission file in our `compute-platform` repo in `.github/chainguard/hot-chemistry.sts.yaml`  with the following content:

```yaml
issuer: https://token.actions.githubusercontent.com
subject: repo:Aqemia/hot-chemistry:ref:refs/*

permissions:
  actions: write
  metadata: read
  contents: write
  checks:	write
  issues: write
  packages: write
```

Then on the `hot-chemistry` repo, we have created a workflow (which is on main branch)

```yaml
name: "TEST"
on:
  workflow_dispatch:

permissions:
    id-token: write

jobs:
  update-webapp:
    name: test
    runs-on: ubuntu-22.04
    steps:
      - id: octo-sts
        uses: octo-sts/action@v1.0.0
        with:
          scope: Aqemia/compute-platform
          identity: hot-chemistry
```

The attached screenshot is the error the workflow gave us 

![image (5)](https://github.com/user-attachments/assets/6199c0c5-1a3e-42a4-811a-dddf8b1952c1)

What have we done wrong ? (Is it a bug ?)
(we followed the documentation on this page: [https://github.com/octo-sts/app](https://github.com/octo-sts/app))

# Expected behavior

We receive a generated github token in the output of the step
