### ISSUE TITLE
HTTP error 403

### ISSUE THREAD

**Issue by jezzdk** [octo-sts/action#31]
I've been following the guide on how to set it up, which I think is pretty straight forward, but something is not working and I'm not sure how to debug it.

I'm getting the following error when running the workflow:
```
Run octo-sts/action@main
  with:
    scope: <org>/<repo>
    identity: write-action
    domain: octo-sts.dev
  
Attempt 1 failed. Error: HTTP error! status: 403
Attempt 2 failed. Error: HTTP error! status: 403
Attempt 3 failed. Error: HTTP error! status: 403
Error: Error: Fetch failed after 4 attempts.
    at fetchWithRetry (/home/runner/work/_actions/octo-sts/action/main/index.js:36:11)
    at async main (/home/runner/work/_actions/octo-sts/action/main/index.js:44:22)
```

This is what I have in the workflow:
```
permissions:
  id-token: write
steps:
  - name: Get short lived write token
    uses: octo-sts/action@main
    id: octo-sts
    with:
      scope: <org>/<repo>
      identity: write-action
```

And this is the policy file:
```
# .github/chainguard/write-action.sts.yaml
issuer: https://token.actions.githubusercontent.com
subject: repo:<org>/<repo>:ref:refs/heads/main

permissions:
  contents: write
```

Notes: 
- It's installed on a private repo.
- We're using branch protection rulesets but it still doesn't work if I add octo-sts to the bypass list.

**Comment by cpanato** [comment]
Is the app available for that private repo?

**Comment by jezzdk** [comment]
> Is the app available for that private repo?

Yes the app has been given permission specifically for that repo only.

**Comment by timharris777** [comment]
I'm running into the exact same issue?

**Comment by cpanato** [comment]
we need more information, as i cannot reproduce.

- is this a self-hosted runner? 
- there are other logs?
- any other info will be good

**Comment by jezzdk** [comment]
> we need more information, as i cannot reproduce.
> 
> * is this a self-hosted runner?
> * there are other logs?
> * any other info will be good

It is not a self-hosted runner. I wish I could give more context, but this is all I have, there is nothing else in the logs. It's the [call to the octo-sts app](https://github.com/octo-sts/action/blob/main/index.js#L44) that fails, but I don't know how I can debug it.

**Comment by cpanato** [comment]
> > we need more information, as i cannot reproduce.
> > 
> > * is this a self-hosted runner?
> > * there are other logs?
> > * any other info will be good
> 
> It is not a self-hosted runner. I wish I could give more context, but this is all I have, there is nothing else in the logs. It's the [call to the octo-sts app](https://github.com/octo-sts/action/blob/main/index.js#L44) that fails, but I don't know how I can debug it.

the code of the workflow helps as well

**Comment by aviadhahami** [comment]
Hey @cpanato we run into the same bug where we get 403 from the `octo-sts` action.

Setup:
- We used the supplied demo workflow from the readme
- (doubly) Verified that the `octo-sts` app  is installed w/ all perms
- Tested various releases (pinned the action's sha) 

all of these and no good, any idea?

**Comment by anthony-jane** [comment]
Getting the same in my POC
```
Attempt 1 failed. Error: HTTP error! status: 403
Attempt 2 failed. Error: HTTP error! status: 403
Attempt 3 failed. Error: HTTP error! status: 403
Error: Error: Fetch failed after 4 attempts.
    at fetchWithRetry (/home/runner/work/_actions/octo-sts/action/e480437973a6f6ac2e9caa40ecabedc870d76395/index.js:36:11)
    at async main (/home/runner/work/_actions/octo-sts/action/e480437973a6f6ac2e9caa40ecabedc870d76395/index.js:48:22)
```

Just trying to test a simple clone of a third party repo from my repo `org/bar`
```
      - uses: octo-sts/action@e480437973a6f6ac2e9caa40ecabedc870d76395 # v1.0.1
        id: octo-sts
        with:
          scope: foo
          identity: octosts

      - name: Checkout mapping repository
        uses: actions/checkout@v4
        with:
          repository: foo
          ref: main
          token: ${{ steps.octo-sts.outputs.token }}
```

The octosts.sts.yaml in the `foo`:
```
issuer: https://token.actions.githubusercontent.com
subject: repo:org/bar:ref:*
permissions:
  contents: read
```
